version: "3"
services:
  nginx:
    container_name: nginx
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/ssl:/etc/nginx/certs
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public

  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
