version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 9090:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        REACT_APP_API_BASE_URL: http://localhost:5000/api
    expose:
      - 3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    depends_on:
      - backend
