version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/React-App-Flask-SSL/src/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/etc/nginx/certs

  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

stdin_open: true
tty: true
