version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/React-App-Flask-SSL/src/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/ssl:/etc/nginx/certs

  backend:
    restart: always
    container_name: backend
    build: ./backend
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: https://demo.ahmedbesbes.com/api
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    depends_on:
      - backend
